#!/bin/sh

NODE_PATH="/home/ziggi/expresso-maacom/backend"
NODE_PATH="$NODE_PATH:/home/ziggi/expresso-maacom/backend"
NODE_PATH="$NODE_PATH:/home/ziggi/expresso-maacom/backend/models"
NODE_PATH="$NODE_PATH:/home/ziggi/expresso-maacom/backend/controllers"
NODE_PATH="$NODE_PATH:/home/ziggi/expresso-maacom/backend/utils"
NODE_PATH="$NODE_PATH:/home/ziggi/expresso-maacom/backend/plugins"
export NODE_PATH

NODE_ENV=production
export NODE_ENV

cd /home/ziggi/expresso-maacom/backend && /usr/local/bin/node /home/ziggi/expresso-maacom/backend/exserv.js $@
#EOF


