#!/bin/sh

NODE_PATH="/home/ziggi/PMM/projects/wcm/backend"
NODE_PATH="$NODE_PATH:/home/ziggi/PMM/projects/wcm/backend"
NODE_PATH="$NODE_PATH:/home/ziggi/PMM/projects/wcm/backend/models"
NODE_PATH="$NODE_PATH:/home/ziggi/PMM/projects/wcm/backend/controllers"
NODE_PATH="$NODE_PATH:/home/ziggi/PMM/projects/wcm/backend/utils"
NODE_PATH="$NODE_PATH:/home/ziggi/PMM/projects/wcm/backend/plugins"
NODE_PATH="$NODE_PATH:/home/ziggi/PMM/projects/wcm/backend/routers"
export NODE_PATH

NODE_ENV=production
export NODE_ENV

cd /home/ziggi/PMM/projects/wcm/backend && /usr/local/bin/node /home/ziggi/PMM/projects/wcm/backend/exserv.js $@
#EOF


