#!/bin/sh
#
# $Id$
#
# PROVIDE: lorem
# REQUIRE: LOGIN

. /etc/rc.subr

name="lorem"
rcvar="lorem_enable"

pidfile="/home/ziggi/lorem/backend/run/pid"
command="/usr/local/sbin/${name}"
command_args="--daemon"
procname="/usr/local/bin/node"
#command_interpreter="/usr/local/bin/node"

load_rc_config ${name}

: ${lorem_enable:="NO"}

run_rc_command "$1"
#EOF
