#!/bin/sh
#
# $Id$
#
# PROVIDE: wcm
# REQUIRE: LOGIN

. /etc/rc.subr

name="wcm"
rcvar="wcm_enable"

pidfile="/home/ziggi/PMM/projects/wcm/backend/run/pid"
command="/usr/local/sbin/${name}"
command_args="--daemon"
procname="/usr/local/bin/node"
#command_interpreter="/usr/local/bin/node"

load_rc_config ${name}

: ${wcm_enable:="NO"}

run_rc_command "$1"
#EOF
